# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rank_card_machine.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 494)
        MainWindow.setMinimumSize(QtCore.QSize(543, 494))
        MainWindow.setMaximumSize(QtCore.QSize(543, 494))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 170, 71, 31))
        self.label_4.setMinimumSize(QtCore.QSize(71, 31))
        self.label_4.setMaximumSize(QtCore.QSize(71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 180, 91, 31))
        self.label_5.setMinimumSize(QtCore.QSize(91, 31))
        self.label_5.setMaximumSize(QtCore.QSize(91, 31))
        self.label_5.setObjectName("label_5")
        self.Enter = QtWidgets.QPushButton(self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(400, 350, 111, 31))
        self.Enter.setMinimumSize(QtCore.QSize(111, 31))
        self.Enter.setMaximumSize(QtCore.QSize(111, 31))
        self.Enter.setObjectName("Enter")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 91, 31))
        self.label_3.setMinimumSize(QtCore.QSize(91, 31))
        self.label_3.setMaximumSize(QtCore.QSize(91, 31))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 300, 91, 31))
        self.label_8.setMinimumSize(QtCore.QSize(91, 31))
        self.label_8.setMaximumSize(QtCore.QSize(91, 31))
        self.label_8.setObjectName("label_8")
        self.Male = QtWidgets.QRadioButton(self.centralwidget)
        self.Male.setGeometry(QtCore.QRect(400, 240, 61, 31))
        self.Male.setMinimumSize(QtCore.QSize(61, 31))
        self.Male.setMaximumSize(QtCore.QSize(61, 31))
        self.Male.setObjectName("Male")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 350, 91, 31))
        self.label_9.setMinimumSize(QtCore.QSize(91, 31))
        self.label_9.setMaximumSize(QtCore.QSize(91, 31))
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 471, 20))
        self.label.setMinimumSize(QtCore.QSize(471, 20))
        self.label.setMaximumSize(QtCore.QSize(471, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Female = QtWidgets.QRadioButton(self.centralwidget)
        self.Female.setGeometry(QtCore.QRect(400, 210, 61, 31))
        self.Female.setMinimumSize(QtCore.QSize(61, 31))
        self.Female.setMaximumSize(QtCore.QSize(61, 31))
        self.Female.setObjectName("Female")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 91, 31))
        self.label_2.setMinimumSize(QtCore.QSize(91, 31))
        self.label_2.setMaximumSize(QtCore.QSize(91, 31))
        self.label_2.setObjectName("label_2")
        self.RollNoBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.RollNoBox.setGeometry(QtCore.QRect(140, 100, 201, 31))
        self.RollNoBox.setMinimumSize(QtCore.QSize(201, 31))
        self.RollNoBox.setMaximumSize(QtCore.QSize(201, 31))
        self.RollNoBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.RollNoBox.setObjectName("RollNoBox")
        self.MatBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.MatBox.setGeometry(QtCore.QRect(140, 260, 201, 31))
        self.MatBox.setMinimumSize(QtCore.QSize(201, 31))
        self.MatBox.setMaximumSize(QtCore.QSize(201, 31))
        self.MatBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.MatBox.setObjectName("MatBox")
        self.SciBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.SciBox.setGeometry(QtCore.QRect(140, 300, 201, 31))
        self.SciBox.setMinimumSize(QtCore.QSize(201, 31))
        self.SciBox.setMaximumSize(QtCore.QSize(201, 31))
        self.SciBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.SciBox.setObjectName("SciBox")
        self.SocBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.SocBox.setGeometry(QtCore.QRect(140, 350, 201, 31))
        self.SocBox.setMinimumSize(QtCore.QSize(201, 31))
        self.SocBox.setMaximumSize(QtCore.QSize(201, 31))
        self.SocBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.SocBox.setObjectName("SocBox")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 220, 91, 31))
        self.label_6.setMinimumSize(QtCore.QSize(91, 31))
        self.label_6.setMaximumSize(QtCore.QSize(91, 31))
        self.label_6.setObjectName("label_6")
        self.Others = QtWidgets.QRadioButton(self.centralwidget)
        self.Others.setGeometry(QtCore.QRect(400, 270, 71, 31))
        self.Others.setMinimumSize(QtCore.QSize(71, 31))
        self.Others.setMaximumSize(QtCore.QSize(71, 31))
        self.Others.setObjectName("Others")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 260, 91, 31))
        self.label_7.setMinimumSize(QtCore.QSize(91, 31))
        self.label_7.setMaximumSize(QtCore.QSize(91, 31))
        self.label_7.setObjectName("label_7")
        self.LangBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.LangBox.setGeometry(QtCore.QRect(140, 180, 201, 31))
        self.LangBox.setMinimumSize(QtCore.QSize(201, 31))
        self.LangBox.setMaximumSize(QtCore.QSize(201, 31))
        self.LangBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.LangBox.setObjectName("LangBox")
        self.EngBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.EngBox.setGeometry(QtCore.QRect(140, 220, 201, 31))
        self.EngBox.setMinimumSize(QtCore.QSize(201, 31))
        self.EngBox.setMaximumSize(QtCore.QSize(201, 31))
        self.EngBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.EngBox.setObjectName("EngBox")
        self.NameBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.NameBox.setGeometry(QtCore.QRect(140, 60, 371, 31))
        self.NameBox.setMinimumSize(QtCore.QSize(371, 31))
        self.NameBox.setMaximumSize(QtCore.QSize(371, 31))
        self.NameBox.setObjectName("NameBox")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 150, 471, 20))
        self.label_10.setMinimumSize(QtCore.QSize(471, 20))
        self.label_10.setMaximumSize(QtCore.QSize(471, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Sex / Gender"))
        self.label_5.setText(_translate("MainWindow", "Language        :"))
        self.Enter.setText(_translate("MainWindow", "Enter"))
        self.label_3.setText(_translate("MainWindow", "Roll No             :"))
        self.label_8.setText(_translate("MainWindow", "Science          :"))
        self.Male.setText(_translate("MainWindow", "Male"))
        self.label_9.setText(_translate("MainWindow", "Social            :"))
        self.label.setText(_translate("MainWindow", "RANK CARD MACHINE"))
        self.Female.setText(_translate("MainWindow", "Female"))
        self.label_2.setText(_translate("MainWindow", "Name                :"))
        self.label_6.setText(_translate("MainWindow", "English            :"))
        self.Others.setText(_translate("MainWindow", "Others"))
        self.label_7.setText(_translate("MainWindow", "Maths             :"))
        self.label_10.setText(_translate("MainWindow", "ENTER THE STUDENTS MARK DETAILS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

