# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rank_card_machine.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 494)
        MainWindow.setMinimumSize(QtCore.QSize(543, 494))
        MainWindow.setMaximumSize(QtCore.QSize(543, 494))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sex = QtWidgets.QLabel(self.centralwidget)
        self.sex.setGeometry(QtCore.QRect(400, 170, 71, 31))
        self.sex.setMinimumSize(QtCore.QSize(71, 31))
        self.sex.setMaximumSize(QtCore.QSize(71, 31))
        self.sex.setObjectName("sex")
        self.lang = QtWidgets.QLabel(self.centralwidget)
        self.lang.setGeometry(QtCore.QRect(40, 180, 91, 31))
        self.lang.setMinimumSize(QtCore.QSize(91, 31))
        self.lang.setMaximumSize(QtCore.QSize(91, 31))
        self.lang.setObjectName("lang")
        self.Enter = QtWidgets.QPushButton(self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(400, 350, 111, 31))
        self.Enter.setMinimumSize(QtCore.QSize(111, 31))
        self.Enter.setMaximumSize(QtCore.QSize(111, 31))
        self.Enter.setObjectName("Enter")
        self.roll_no = QtWidgets.QLabel(self.centralwidget)
        self.roll_no.setGeometry(QtCore.QRect(40, 100, 91, 31))
        self.roll_no.setMinimumSize(QtCore.QSize(91, 31))
        self.roll_no.setMaximumSize(QtCore.QSize(91, 31))
        self.roll_no.setObjectName("roll_no")
        self.sci = QtWidgets.QLabel(self.centralwidget)
        self.sci.setGeometry(QtCore.QRect(40, 300, 91, 31))
        self.sci.setMinimumSize(QtCore.QSize(91, 31))
        self.sci.setMaximumSize(QtCore.QSize(91, 31))
        self.sci.setObjectName("sci")
        self.Male = QtWidgets.QRadioButton(self.centralwidget)
        self.Male.setGeometry(QtCore.QRect(400, 240, 61, 31))
        self.Male.setMinimumSize(QtCore.QSize(61, 31))
        self.Male.setMaximumSize(QtCore.QSize(61, 31))
        self.Male.setObjectName("Male")
        self.soc = QtWidgets.QLabel(self.centralwidget)
        self.soc.setGeometry(QtCore.QRect(40, 350, 91, 31))
        self.soc.setMinimumSize(QtCore.QSize(91, 31))
        self.soc.setMaximumSize(QtCore.QSize(91, 31))
        self.soc.setObjectName("soc")
        self.rank_card_machine = QtWidgets.QLabel(self.centralwidget)
        self.rank_card_machine.setGeometry(QtCore.QRect(40, 30, 471, 20))
        self.rank_card_machine.setMinimumSize(QtCore.QSize(471, 20))
        self.rank_card_machine.setMaximumSize(QtCore.QSize(471, 20))
        self.rank_card_machine.setAlignment(QtCore.Qt.AlignCenter)
        self.rank_card_machine.setObjectName("rank_card_machine")
        self.Female = QtWidgets.QRadioButton(self.centralwidget)
        self.Female.setGeometry(QtCore.QRect(400, 210, 61, 31))
        self.Female.setMinimumSize(QtCore.QSize(61, 31))
        self.Female.setMaximumSize(QtCore.QSize(61, 31))
        self.Female.setObjectName("Female")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(40, 60, 91, 31))
        self.name.setMinimumSize(QtCore.QSize(91, 31))
        self.name.setMaximumSize(QtCore.QSize(91, 31))
        self.name.setObjectName("name")
        self.RollNoBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.RollNoBox.setGeometry(QtCore.QRect(140, 100, 201, 31))
        self.RollNoBox.setMinimumSize(QtCore.QSize(201, 31))
        self.RollNoBox.setMaximumSize(QtCore.QSize(201, 31))
        self.RollNoBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.RollNoBox.setObjectName("RollNoBox")
        self.MatBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.MatBox.setGeometry(QtCore.QRect(140, 260, 201, 31))
        self.MatBox.setMinimumSize(QtCore.QSize(201, 31))
        self.MatBox.setMaximumSize(QtCore.QSize(201, 31))
        self.MatBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.MatBox.setObjectName("MatBox")
        self.SciBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.SciBox.setGeometry(QtCore.QRect(140, 300, 201, 31))
        self.SciBox.setMinimumSize(QtCore.QSize(201, 31))
        self.SciBox.setMaximumSize(QtCore.QSize(201, 31))
        self.SciBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.SciBox.setObjectName("SciBox")
        self.SocBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.SocBox.setGeometry(QtCore.QRect(140, 350, 201, 31))
        self.SocBox.setMinimumSize(QtCore.QSize(201, 31))
        self.SocBox.setMaximumSize(QtCore.QSize(201, 31))
        self.SocBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.SocBox.setObjectName("SocBox")
        self.eng = QtWidgets.QLabel(self.centralwidget)
        self.eng.setGeometry(QtCore.QRect(40, 220, 91, 31))
        self.eng.setMinimumSize(QtCore.QSize(91, 31))
        self.eng.setMaximumSize(QtCore.QSize(91, 31))
        self.eng.setObjectName("eng")
        self.Others = QtWidgets.QRadioButton(self.centralwidget)
        self.Others.setGeometry(QtCore.QRect(400, 270, 71, 31))
        self.Others.setMinimumSize(QtCore.QSize(71, 31))
        self.Others.setMaximumSize(QtCore.QSize(71, 31))
        self.Others.setObjectName("Others")
        self.mat = QtWidgets.QLabel(self.centralwidget)
        self.mat.setGeometry(QtCore.QRect(40, 260, 91, 31))
        self.mat.setMinimumSize(QtCore.QSize(91, 31))
        self.mat.setMaximumSize(QtCore.QSize(91, 31))
        self.mat.setObjectName("mat")
        self.LangBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.LangBox.setGeometry(QtCore.QRect(140, 180, 201, 31))
        self.LangBox.setMinimumSize(QtCore.QSize(201, 31))
        self.LangBox.setMaximumSize(QtCore.QSize(201, 31))
        self.LangBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.LangBox.setObjectName("LangBox")
        self.EngBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.EngBox.setGeometry(QtCore.QRect(140, 220, 201, 31))
        self.EngBox.setMinimumSize(QtCore.QSize(201, 31))
        self.EngBox.setMaximumSize(QtCore.QSize(201, 31))
        self.EngBox.setInputMethodHints(QtCore.Qt.ImhMultiLine|QtCore.Qt.ImhPreferNumbers)
        self.EngBox.setObjectName("EngBox")
        self.NameBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.NameBox.setGeometry(QtCore.QRect(140, 60, 371, 31))
        self.NameBox.setMinimumSize(QtCore.QSize(371, 31))
        self.NameBox.setMaximumSize(QtCore.QSize(371, 31))
        self.NameBox.setObjectName("NameBox")
        self.enter_the_student_details = QtWidgets.QLabel(self.centralwidget)
        self.enter_the_student_details.setGeometry(QtCore.QRect(40, 150, 471, 20))
        self.enter_the_student_details.setMinimumSize(QtCore.QSize(471, 20))
        self.enter_the_student_details.setMaximumSize(QtCore.QSize(471, 20))
        self.enter_the_student_details.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_the_student_details.setObjectName("enter_the_student_details")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sex.setText(_translate("MainWindow", "Sex / Gender"))
        self.lang.setText(_translate("MainWindow", "Language        :"))
        self.Enter.setText(_translate("MainWindow", "Enter"))
        self.roll_no.setText(_translate("MainWindow", "Roll No             :"))
        self.sci.setText(_translate("MainWindow", "Science          :"))
        self.Male.setText(_translate("MainWindow", "Male"))
        self.soc.setText(_translate("MainWindow", "Social            :"))
        self.rank_card_machine.setText(_translate("MainWindow", "RANK CARD MACHINE"))
        self.Female.setText(_translate("MainWindow", "Female"))
        self.name.setText(_translate("MainWindow", "Name                :"))
        self.eng.setText(_translate("MainWindow", "English            :"))
        self.Others.setText(_translate("MainWindow", "Others"))
        self.mat.setText(_translate("MainWindow", "Maths             :"))
        self.enter_the_student_details.setText(_translate("MainWindow", "ENTER THE STUDENTS MARK DETAILS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

